### ISSUE TITLE
大佬文档里面的使用打不开

### ISSUE THREAD

**Issue by zxxhz** [wxyShine/halo-plugin-webhook#4]
[https://www.wxy97.com/docs/halo-plugin-webhook/use](https://www.wxy97.com/docs/halo-plugin-webhook/use)
这个链接
支持大佬继续开发，希望早日实现更新文章事件

**Comment by wxyShine** [comment]
![image](https://github.com/wxyShine/halo-plugin-webhook/assets/42802152/a0c99c1f-9d59-4d5f-b4e8-27da306596d0)
可以正常打开的呀 你再试下看看？

**Comment by zxxhz** [comment]
今天可以了

**Comment by wxyShine** [comment]
> 今天可以了

可能估计碰巧那会在更新程序
